// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ospchqrvtibneuxmsdgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zcGNocXJ2dGlibmV1eG1zZGdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDk4NTgsImV4cCI6MjA2NzI4NTg1OH0.s_qneD9B5iL6KWxzqhAgjVFb4pnzET4buTT69ZCaEYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});